feature/visit timeline
dvsa/cvs-app-mobile-ionic-5 pull request #12
Opened 2022-04-01 14:04 UTC by tomcrawleyy

Ionic 3
![MicrosoftTeams-image](https://user-images.githubusercontent.com/28736958/161553977-1d26819f-d7cb-482b-b010-73b76f85bf99.png)
>

Ionic 5
<img width="423" alt="image" src="https://user-images.githubusercontent.com/28736958/161554074-3e527f1e-ceb5-452a-b9bd-15472a1a7a52.png">

2022-04-04 10:51 UTC, Cullima requested changes

2022-04-04 10:51 UTC, Cullima commented on src/app/pages/visit/visit-timeline/visit-timeline.spec.ts
> +    // it('should display the site closed alert if visit was previously closed', async () => {
why are all these tsts disabled?

2022-04-04 10:52 UTC, tomcrawleyy commented on src/app/pages/visit/visit-timeline/visit-timeline.spec.ts
> +    // it('should display the site closed alert if visit was previously closed', async () => {
they are related to wait times, which is disabled in the main app, we also don't know if is ever going to be re-introduced, so we decided not to waste time fiddling trying to get related unit tests to work

2022-04-05 09:43 UTC, Cullima approved these changes

2022-04-08 13:22 UTC, merged